on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release list
      - name: test release
        run: echo ${{ github.event_name }}
      - name: Change base_sha
        id: change-base-sha
        env:
          GH_TOKEN: ${{ github.token }}
        if: github.event_name == 'release'
        run: | 
          strTag=$(gh release list -L 2 | head -n 2 | tail -n 1)
          echo $strTag
          echo $tag=$(echo $strTag | tr " " "\n" | head -n1)
          echo $tag
