on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release list
      - name: test release
        run: echo ${{ github.event_name }}
