on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release list
      - name: test release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: git fetch --tags && git describe --tags --abbrev=0 --match 'v*' --exclude '*-rc*' HEAD
