name: Matrix test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mafiapigs-macos
            metaId: 2177361
            otherId: 2177360
          - target: project-windows
            metaId: 2177362
            otherId: 2177360
    outputs:
      results: ${{ steps.setvars.outputs.matrix }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          echo "matrix=${{matrix.target}}" >> $GITHUB_OUTPUT

  check-matrix:
    runs-on:  ubuntu-22.04
    needs: [ matrix ]
    env:
      test: ${{ needs.matrix.outputs.results }}
    steps:
      - name: Set variables
        id: setvars
        run: | 
          printenv