name: Matrix test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mafiapigs-macos
            metaId: 2177361
            otherId: 2177360
          - target: project-windows
            metaId: 2177362
            otherId: 2177360
    outputs:
      mafiapigs-macos: ${{ steps.setvars.outputs.mafiapigs-macos }}
      project-windows: ${{ steps.setvars.outputs.project-windows }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          echo "${{matrix.target}}=olá" >> $GITHUB_OUTPUT

  check-matrix:
    runs-on:  ubuntu-22.04
    needs: [ matrix ]
    env:
      mafiapigs-macos: ${{ needs.matrix.outputs.mafiapigs-macos }}
      project-windows: ${{ needs.matrix.outputs.project-windows }}
    steps:
      - name: Set variables
        id: setvars
        run: | 
          printenv