name: Matrix test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-22.04
    env:
      RESULTS: ''
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mafiapigs-macos
            metaId: 2177361
            otherId: 2177360
          - target: project-windows
            metaId: 2177362
            otherId: 2177360
    outputs:
      mafiapigs-macos: ${{ steps.setvars.outputs.mafiapigs-macos }}
      project-windows: ${{ steps.setvars.outputs.project-windows }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            .github
      - name: Set variables
        id: setvars
        run: |
          $RESULTS=$(./.github/workflows/compare_bundles.sh)
        env:
          SERVICE_NAME: ${{ matrix.target }}
      - name: printenv
        run: |
          echo '######################'
          printenv
  # check-matrix:
  #   runs-on:  ubuntu-22.04
  #   needs: [ matrix ]
  #   env:
  #     mafiapigs-macos: ${{ needs.matrix.outputs.mafiapigs-macos }}
  #     project-windows: ${{ needs.matrix.outputs.project-windows }}
  #   steps:
  #     - name: Set variables
  #       id: setvars
  #       run: | 
  #         printenv